apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-service-ess
  namespace: sync-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sync-service-ess
  template:
    metadata:
      labels:
        name: sync-service-ess
    spec:
      serviceAccountName: sync-service-ess
      containers:
        - name: ess
          image: quay.io/open-cluster-management-hub-of-hubs/leaf-hub-sync-service-ess:stable
          imagePullPolicy: Always
          env:
            - name: HTTPCSSHost
              value: "$CSS_HOST"
            - name: HTTPCSSPort
              value: "80"
            - name: DESTINATION_ID
              value: "$LH_ID"
            - name: LISTENING_TYPE
              value: unsecure
            - name: UNSECURE_LISTENING_PORT
              value: "8090"
            - name: HTTP_POLLING_INTERVAL
              value: "5"
